import type { IrDocument, IrOperation, IrSchema, IrService, IrType } from "../ir.ts";
import type { EmitContext } from "./ts-writer.ts";
import { collectRefs } from "../ir.ts";
/**
 * Emits the generated `types/` folder:
 * - `types/common.ts` — types referenced by 2+ services (or unreferenced)
 * - `types/<service>.ts` — types used exclusively by one service
 * - `types/index.ts` — barrel re-exporting everything
 */
import { buildJsDoc } from "../jsdoc.ts";
import { NameRegistry } from "../names.ts";
import { printProperty, printType, relativeImport } from "./ts-writer.ts";

export const GENERATED_HEADER =
  "// Generated by @narthia/openapi-sdk-generator. Do not edit manually.";

export interface TypePartition {
  common: IrSchema[];
  /** service name → schemas exclusive to it (services without local types are absent). */
  perService: Map<string, IrSchema[]>;
  /** schema name → file base it lives in ("common" or a service's type file base). */
  fileOf: Map<string, string>;
  /** service name → type file base name (collision-safe against "common"/"index"). */
  serviceFileBase: Map<string, string>;
}

/** Decide which file every named type lives in (see plan: usage-analysis + common closure). */
export function partitionSchemas(doc: IrDocument): TypePartition {
  const schemaByName = new Map(doc.schemas.map((s) => [s.name, s]));

  // Transitive ref closure of one service's operations.
  const closureOf = (service: IrService): Set<string> => {
    const seen = new Set<string>();
    const queue = service.operations.flatMap(operationTypes).flatMap((t) => [...collectRefs(t)]);
    while (queue.length > 0) {
      const name = queue.pop()!;
      if (seen.has(name)) continue;
      seen.add(name);
      const schema = schemaByName.get(name);
      if (schema) queue.push(...collectRefs(schema.type));
    }
    return seen;
  };

  const closures = new Map(doc.services.map((s) => [s.name, closureOf(s)]));

  const usedBy = new Map<string, string[]>();
  for (const [serviceName, closure] of closures) {
    for (const typeName of closure) {
      usedBy.set(typeName, [...(usedBy.get(typeName) ?? []), serviceName]);
    }
  }

  // Common = shared by 2+ services or referenced by nothing; then close over
  // refs so a common type never imports from a service file.
  const common = new Set<string>(
    doc.schemas.map((s) => s.name).filter((name) => (usedBy.get(name)?.length ?? 0) !== 1)
  );
  const queue = [...common];
  while (queue.length > 0) {
    const schema = schemaByName.get(queue.pop()!);
    if (!schema) continue;
    for (const ref of collectRefs(schema.type)) {
      if (!common.has(ref)) {
        common.add(ref);
        queue.push(ref);
      }
    }
  }

  const files = new NameRegistry();
  files.claim("common");
  files.claim("index");
  const serviceFileBase = new Map(doc.services.map((s) => [s.name, files.claim(s.fileName)]));

  const partition: TypePartition = {
    common: [],
    perService: new Map(),
    fileOf: new Map(),
    serviceFileBase,
  };
  for (const schema of doc.schemas) {
    if (common.has(schema.name)) {
      partition.common.push(schema);
      partition.fileOf.set(schema.name, "common");
      continue;
    }
    const serviceName = usedBy.get(schema.name)![0]!;
    const bucket = partition.perService.get(serviceName) ?? [];
    bucket.push(schema);
    partition.perService.set(serviceName, bucket);
    partition.fileOf.set(schema.name, serviceFileBase.get(serviceName)!);
  }
  return partition;
}

/** All types a single operation's signature touches. */
export function operationTypes(op: IrOperation): IrType[] {
  return [
    ...op.pathParams.map((p) => p.type),
    ...op.queryParams.map((p) => p.type),
    ...op.headerParams.map((p) => p.type),
    ...(op.body ? [op.body.type] : []),
    op.response.type,
  ];
}

/** Render every file of the `types/` folder as path → contents. */
export function emitTypesFolder(
  doc: IrDocument,
  partition: TypePartition,
  ctx: EmitContext
): Map<string, string> {
  const files = new Map<string, string>();
  const barrelEntries: string[] = [];

  if (partition.common.length > 0) {
    files.set("types/common.ts", renderTypeFile(partition.common, partition, ctx, "common"));
    barrelEntries.push("common");
  }
  for (const service of doc.services) {
    const schemas = partition.perService.get(service.name);
    if (!schemas || schemas.length === 0) continue;
    const base = partition.serviceFileBase.get(service.name)!;
    files.set(`types/${base}.ts`, renderTypeFile(schemas, partition, ctx, base));
    barrelEntries.push(base);
  }

  const barrel = [
    GENERATED_HEADER,
    "",
    ...barrelEntries.map((base) => `export * from "${relativeImport(ctx, `./${base}`)}";`),
    "",
  ].join("\n");
  files.set("types/index.ts", barrel);
  return files;
}

function renderTypeFile(
  schemas: IrSchema[],
  partition: TypePartition,
  ctx: EmitContext,
  selfBase: string
): string {
  // Imports for refs living in other type files (service files only ever import common).
  const external = new Set<string>();
  for (const schema of schemas) {
    for (const ref of collectRefs(schema.type)) {
      const fileBase = partition.fileOf.get(ref);
      if (fileBase !== undefined && fileBase !== selfBase) external.add(ref);
    }
  }

  const parts: string[] = [GENERATED_HEADER, ""];
  if (external.size > 0) {
    const names = [...external].sort().join(", ");
    parts.push(`import type { ${names} } from "${relativeImport(ctx, "./common")}";`, "");
  }
  for (const schema of schemas) {
    parts.push(renderNamedSchema(schema), "");
  }
  return `${parts.join("\n").trimEnd()}\n`;
}

/** Render one named type: plain objects become interfaces, everything else a type alias. */
function renderNamedSchema(schema: IrSchema): string {
  const doc = buildJsDoc({
    description: schema.docs.description,
    deprecated: schema.docs.deprecated,
    default: schema.docs.default,
    format: schema.docs.format,
    example: schema.docs.example,
  });
  const lines: string[] = [];
  if (doc) lines.push(doc);

  const type = schema.type;
  const isInterface =
    type.kind === "object" &&
    type.properties.length > 0 &&
    (type.additionalProperties === undefined || type.additionalProperties === true);

  if (isInterface && type.kind === "object") {
    lines.push(`export interface ${schema.name} {`);
    for (const prop of type.properties) {
      lines.push(...printProperty(prop, "  "));
    }
    if (type.additionalProperties === true) lines.push("  [key: string]: unknown;");
    lines.push("}");
  } else {
    lines.push(`export type ${schema.name} = ${printType(type)};`);
  }
  return lines.join("\n");
}
