/**
 * Runtime client core for SDKs generated by `@narthia/openapi-sdk-generator`.
 *
 * Generated code imports {@link createClient} and the runtime types from this
 * subpath; transports live in their own subpaths (e.g. `./transports/http`).
 */
export { createClient } from "./client.ts";
export { ApiError } from "./errors.ts";
export { encodeBody, interpolatePath, serializeQuery } from "./serialize.ts";
export type {
  AuthConfig,
  BodyType,
  ClientConfig,
  ClientContext,
  HttpMethod,
  OperationSpec,
  ResponseType,
  Transport,
  TransportRequest,
  TransportResponse,
  ValueOrFactory,
} from "./types.ts";
